// Regenerates soteria-frontend/src/chain/custody/abi.ts from the Foundry build. Run after `forge build`.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
const root = fileURLToPath(new URL("../../", import.meta.url));
const { abi } = JSON.parse(readFileSync(root + "contracts/out/Custody.sol/Custody.json", "utf8"));
writeFileSync(
  root + "soteria-frontend/src/chain/custody/abi.ts",
  "// Generated by contracts/tools/custody-abi.mjs from contracts/out/Custody.sol/Custody.json. Do not edit.\n" +
    "export const custodyAbi = " + JSON.stringify(abi, null, 2) + " as const;\n",
);
console.log("abi.ts written:", abi.length, "entries");
