import { FleetAsset, TransitRoute, IncidentAlert, SoteriaConsensusItem, FleetMetrics, SensorCompartment, TrainStop } from '../types/fleet';
import { SCENARIOS, Scenario, RawTrain, RawIncident, RawWagon, JourneyStop, INITIAL_FOCUS_CASE } from './scenarios';
import { corridorById, measuredCorridor } from '../map/railGeometry';
// Real Soteria agent results, generated by Soteria/scripts/export_frontend.py
import SOTERIA_EXPORT from './soteria.json';

export interface SoteriaEvent { seq: number; t: number; type: string;[key: string]: unknown }
export interface SoteriaDecision {
  status: 'decided' | 'blocked';
  code?: string;
  measures: { code: string; label: string }[];
  tier?: 1 | 2 | 3;
  tierLabel?: string;
  keysNeeded?: number;
  grants?: string[];
  reasonLabel?: string;
  coverage?: { answered: number; asked: number };
  receiptHash?: string;
  decidedBy?: 'llm' | 'policy_fallback' | 'policy';
  model?: string;
  rationale?: string;
}
type SoteriaResult = Pick<IncidentAlert, 'recommendation' | 'soteriaTier' | 'marketSensitive'> & {
  caseId: string;
  blockedChannels?: string[];
  trainId: string;
  consensus: SoteriaConsensusItem[];
  decision: SoteriaDecision;
  events: SoteriaEvent[];
};
export const SOTERIA_BY_INCIDENT = SOTERIA_EXPORT as unknown as Record<string, SoteriaResult>;

// World overview (compass button) with all continent-spanning incidents.
// The app itself opens on the "initial_focus" scenario, see data/scenarios.json.
export const INITIAL_MAP_CENTER: [number, number] = [-5, 10];
export const INITIAL_MAP_ZOOM = 1.15;
export const INITIAL_MAP_PITCH = 0;
export const INITIAL_MAP_BEARING = 0;

// Routes come from data/scenarios.json; their geometry is the real track centre
// line from OpenStreetMap (src/data/railCorridors.json, scripts/fetch-rail-corridors.mjs).
export const MOCK_ROUTES: TransitRoute[] = SCENARIOS.map(s => ({
  id: s.route.id,
  code: s.route.code,
  name: s.route.name,
  type: 'rail',
  color: s.route.color,
  activeAssetsCount: 1,
  scheduleVarianceMin: s.incident.train_operational === 'immobilized' ? 120 : s.incident.train_operational === 'restricted' ? 35 : 5,
  status: s.incident.severity === 'high' ? 'critical' : s.incident.severity === 'medium' ? 'delayed' : 'optimal',
  coordinates: corridorById(s.route.id)?.coordinates ?? [],
}));

function cargoTypeFromWagons(wagons: RawWagon[]): FleetAsset['cargoType'] {
  if (wagons.some(w => w.cargo_class === 'hazmat')) return 'Chemicals (Hazmat)';
  if (wagons.some(w => w.cargo_class === 'pharmaceutical' || w.cargo_class === 'perishable')) return 'Pharma / Cold Chain';
  return 'Bulk Freight';
}

function statusFromSeverity(severity: RawIncident['severity']): FleetAsset['status'] {
  return severity === 'high' ? 'offline' : 'warning';
}

function buildCompartments(train: RawTrain, incident: RawIncident): SensorCompartment[] {
  return train.wagons.map((wagon) => {
    const damage = incident.affected_wagons.find(aw => aw.wagon_id === wagon.wagon_id);
    const status: SensorCompartment['status'] = damage
      ? (incident.severity === 'high' ? 'critical' : 'warning')
      : 'nominal';
    return {
      id: `${train.train_id}-${wagon.wagon_id}`,
      name: `${wagon.wagon_id} (${wagon.cargo_class.replace('_', ' ')})`,
      temp: wagon.wagon_type === 'refrigerated' ? (status === 'nominal' ? -17.8 : -9.4) : undefined,
      pressure: wagon.wagon_type === 'refrigerated' ? 1.0 : undefined,
      status,
    };
  });
}

function formatDateTime(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleDateString('en-US', { timeZone: 'UTC' }) + ', ' + d.toLocaleTimeString('en-US', { timeZone: 'UTC', hour: '2-digit', minute: '2-digit' });
}

// Minutes from the incident until the timetabled arrival ("07:15 PM"), plus the delay.
// Both times are UTC, see "_comment_journey" in data/scenarios.json.
function minutesToArrival(incidentIso: string, arrivalTime: string, delayMin: number): number {
  const [, hh, mm, ampm] = arrivalTime.match(/^(\d{1,2}):(\d{2}) (AM|PM)$/)!;
  const arrival = (Number(hh) % 12 + (ampm === 'PM' ? 12 : 0)) * 60 + Number(mm);
  const d = new Date(incidentIso);
  const now = d.getUTCHours() * 60 + d.getUTCMinutes();
  return ((arrival - now + 1440) % 1440) + delayMin;
}

const OPERATIONAL_NEXT_STEP: Record<RawIncident['train_operational'], string> = {
  normal: 'Proceeding with caution',
  restricted: 'Waiting for line clearance',
  immobilized: 'Train immobilized — recovery required',
};

// Pin a journey stop at its station on the corridor; without one (or if the
// corridor ends before it) the stop sits at the corridor end instead.
function resolveStop(routeId: string, stop: JourneyStop, fallbackAlongM: number): TrainStop {
  const stations = corridorById(routeId)?.stations ?? [];
  const wanted = stop.station;
  const station = wanted ? stations.find(s => s.name === wanted) ?? stations.find(s => s.name.startsWith(wanted)) : undefined;
  return station
    ? { name: stop.name, alongM: station.along, isStation: true }
    : { name: stop.name, alongM: fallbackAlongM, isStation: false };
}

function buildAssetFromScenario(scenario: Scenario): FleetAsset {
  const { train_data: train, incident, journey } = scenario;
  const routeId = scenario.route.id;
  const corridor = corridorById(routeId)!;
  const line = measuredCorridor(routeId)!;
  const head = corridor.anchorAlongM;
  const hasRefrigerated = train.wagons.some(w => w.wagon_type === 'refrigerated');
  const refrigeratedAffected = incident.affected_wagons.some(aw =>
    train.wagons.find(w => w.wagon_id === aw.wagon_id)?.wagon_type === 'refrigerated'
  );
  const delayMin = incident.train_operational === 'immobilized' ? 120 : incident.train_operational === 'restricted' ? 35 : 5;
  // A restricted train is held in front of the obstruction until the line is cleared
  const speedKmh = incident.train_operational === 'normal' ? scenario.train.speed_kmh ?? 70 : 0;

  return {
    id: `asset-${train.train_id.toLowerCase()}`,
    name: train.train_id,
    type: 'train',
    category: 'Freight Train',
    status: statusFromSeverity(incident.severity),
    statusText: incident.symptom,
    coordinates: line.pointAt(head),
    altitude: 435,
    heading: Math.round(line.bearingAt(head)),
    speedKmh,
    routeId,
    routeName: scenario.location_label.split(',')[0],
    origin: journey.origin.name,
    destination: journey.destination.name,
    departureTime: journey.departure_time,
    arrivalTime: journey.arrival_time,
    routeProgressPct: journey.progress_pct,
    routeLengthKm: journey.route_length_km,
    travelTimeMin: journey.travel_time_min,
    flag: scenario.flag,
    currentStation: scenario.location_label,
    nextStation: OPERATIONAL_NEXT_STEP[incident.train_operational],
    estimatedArrivalMin: incident.train_operational === 'immobilized' ? 0 : minutesToArrival(incident.timestamp, journey.arrival_time, delayMin),
    delayMin,
    cargoType: cargoTypeFromWagons(train.wagons),
    cargoIntegrityPct: Math.round(((train.wagon_count - incident.affected_wagons.length) / train.wagon_count) * 100),
    targetTempC: hasRefrigerated ? -18.0 : undefined,
    currentTempC: hasRefrigerated ? (refrigeratedAffected ? -9.4 : -17.6) : undefined,
    loadPct: Math.min(96, 60 + train.wagon_count * 3),
    connectivity: {
      gps: true,
      lte: true,
      iotSensors: train.wagon_count * 2,
    },
    compartments: buildCompartments(train, incident),
    updatedAt: formatDateTime(incident.timestamp),
    wagons: train.wagons.map(w => ({
      id: w.wagon_id,
      type: w.wagon_type,
      cargoClass: w.cargo_class,
      damaged: incident.affected_wagons.some(aw => aw.wagon_id === w.wagon_id),
      damage: incident.affected_wagons.find(aw => aw.wagon_id === w.wagon_id)?.damage_description,
    })),
    track: {
      corridorId: routeId,
      headAlongM: head,
      startAlongM: head,
      updatedAtMs: Date.now(),
      livery: scenario.train.livery,
      origin: resolveStop(routeId, journey.origin, 0),
      destination: resolveStop(routeId, journey.destination, line.length),
      trackBlocked: incident.track_blocked,
      obstruction: scenario.obstruction && incident.obstruction.present
        ? { aheadM: scenario.obstruction.ahead_m, kind: scenario.obstruction.model }
        : undefined,
    },
  };
}

export const MOCK_ASSETS: FleetAsset[] = SCENARIOS.map(buildAssetFromScenario);

// The train the map opens on, see "initial_focus" in data/scenarios.json
const focusScenario = SCENARIOS.find(s => s.case_id === INITIAL_FOCUS_CASE);
export const INITIAL_FOCUS_ASSET_ID: string | null = focusScenario
  ? `asset-${focusScenario.train_data.train_id.toLowerCase()}`
  : null;

const INCIDENT_TYPE_LABEL: Record<string, string> = {
  damage_and_obstruction: 'Collision & wagon damage',
  obstruction: 'Track obstruction',
};

const RECOMMENDATION_BY_STATE: Record<RawIncident['train_operational'], string> = {
  normal: 'Continue at reduced speed, inspect the affected wagon at the next stop',
  restricted: 'Keep the line closed, dispatch a clearing crew, activate a diversion route for following trains',
  immobilized: 'Alert emergency services, close the line completely, dispatch a recovery train',
};

// "Now" reference for the command-center demo, shortly after the most recent report.
const NOW_REFERENCE = new Date('2026-09-16T18:07:00Z');

function formatTimeAgo(iso: string): string {
  const diffMin = Math.max(0, Math.round((NOW_REFERENCE.getTime() - new Date(iso).getTime()) / 60000));
  if (diffMin < 60) return `${diffMin}m ago`;
  return `${Math.round(diffMin / 60)}h ${diffMin % 60}m ago`;
}

function buildIncidentAlert({ train_data: train, incident, location_label }: Scenario): IncidentAlert {
  const cargoClasses = train.wagons.map(w => w.cargo_class);
  const real = SOTERIA_BY_INCIDENT[incident.incident_id];
  return {
    id: incident.incident_id,
    title: incident.symptom,
    category: INCIDENT_TYPE_LABEL[incident.incident_type] ?? incident.incident_type,
    severity: incident.severity,
    assetId: `asset-${train.train_id.toLowerCase()}`,
    assetName: `Freight train ${train.train_id}`,
    routeCode: location_label.split(',')[0],
    timeAgo: formatTimeAgo(incident.timestamp),
    timestamp: incident.timestamp,
    reportedAt: formatDateTime(incident.timestamp),
    affectedCount: incident.affected_wagons.length > 0
      ? `${incident.affected_wagons.length} of ${train.wagon_count} wagons affected`
      : 'No wagons damaged',
    affectedLocations: [location_label],
    // Real decision from the Soteria backend where present, mock otherwise
    recommendation: real?.recommendation ?? RECOMMENDATION_BY_STATE[incident.train_operational],
    soteriaTier: real?.soteriaTier ?? (incident.severity === 'high' ? 3 : incident.severity === 'medium' ? 2 : 1),
    marketSensitive: real?.marketSensitive ?? (cargoClasses.includes('hazmat') || cargoClasses.includes('pharmaceutical')),
  };
}

// Newest report first, matching how the notification feed reads live incoming reports.
export const MOCK_INCIDENTS: IncidentAlert[] = SCENARIOS
  .map(buildIncidentAlert)
  .sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

export const MOCK_METRICS: FleetMetrics = {
  totalVehicles: MOCK_ASSETS.length,
  trainsCount: MOCK_ASSETS.filter(a => a.type === 'train').length,
  trucksCount: MOCK_ASSETS.filter(a => a.type === 'truck').length,
  inOperationCount: MOCK_ASSETS.filter(a => a.status !== 'offline').length,
  outOfServiceCount: MOCK_ASSETS.filter(a => a.status === 'offline').length,
  operationalEfficiencyPct: 78.3,
  averageVarianceMin: 2.5,
  wagonsInTransit: MOCK_ASSETS.reduce((sum, a) => sum + a.compartments.length, 0),
  activeIncidentsCount: MOCK_INCIDENTS.length,
};
